version: "3.7"

services:
  server:
    container_name: node-dev
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    build: '.'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
    links:
      - db
    networks: 
      - mongo-compose-network
    ports:
      - '4242:4242'

  db:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASS}
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db      

networks:
  mongo-compose-network:
    driver: bridge