### Create
POST http://localhost:4242/items
content-type: application/json

{
    "name": "Star Wars 1",
    "price": 40,
    "quantity": 100
}

### Find All
GET http://localhost:4242/items

### Find One
GET http://localhost:4242/items/65487a79b51a966fdecb909c

### Update
PUT http://localhost:4242/items/65487a79b51a966fdecb909c
content-type: application/json

{
    "name": "Star Wars 1",
    "price": 40,
    "quantity": 70
}

### DELETE
DELETE http://localhost:4242/items/65487a79b51a966fdecb909c